### PR TITLE
Updates to README.md using markdown formatting for legibility.

### PR DESCRIPTION
**Pull request by jeremiah**
- Formatting with Markdown so that commands are clearly defined.
- Added dependencies for Qface, added correct URL for Qface

### CODE REVIEW

**Comment by sashko** [comment]
1. Get rid of 24c86c2
2. Merge fa8fcf2, 90b8517 and 5fc2d72
3. Better title, please

**Comment by jeremiah** [comment]
This should be better now, but I worry about the .gitmodules stuff -- I don't want to overwrite someone else's changes.

**Review by frznlogic — CHANGES_REQUESTED** [review]
The commit message doesn't mention the added/changed stuff? The commit actually swaps an URL and adds a Build dependencies section.

**Comment by jeremiah** [comment]
Updated based on feedback -- thanks!

**Comment by sashko** [comment]
@jeremiah you need to specify what kind of updates you're making; also titles in English do not end with a dot

**Comment by jeremiah** [comment]
The update info is in the commit message. Does it really matter if there is a period at the end of the headline? Really?

**Comment by sashko** [comment]
Yes, it does. Also, there is a limit of 50 characters on the length of the title.

**Comment by sashko** [comment]
Not to mention the merge conflict.

**Review by sashko — CHANGES_REQUESTED** [review]
Split commits and fix commit message, please.

**Comment by jeremiah** [comment]
I need to work on the merge conflict because I don't really understand what will happen if we merge this. Obviously we need to fix the conflict, but I need to speak with the maintainer about the submodule and what I"m breaking.

**Comment by sashko** [comment]
@jeremiah you've mixed it; just change the title to something like "Fix markdown syntax in README and update qface submodule URI" and good to go

**Comment by sashko** [comment]
Ah, sorry, The merge conflict is still here. You're trying to edit the following line:

`url = git@github.com:Pelagicore/qface.git`

which doesn't exist anymore. It now looks like:

`url = ../qface.git`

so you will have to rebase

**Pull request closed without merging**
